// Code generated by "stringer -type=FrostReportStatus -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FrostReportStatusFrostRisk-0]
	_ = x[FrostReportStatusNoRisk-1]
}

const _FrostReportStatus_name = "Frost RiskNo Risk"

var _FrostReportStatus_index = [...]uint8{0, 10, 17}

func (i FrostReportStatus) String() string {
	if i < 0 || i >= FrostReportStatus(len(_FrostReportStatus_index)-1) {
		return "FrostReportStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FrostReportStatus_name[_FrostReportStatus_index[i]:_FrostReportStatus_index[i+1]]
}
