#! /bin/bash

set -euo pipefail

tag=${1};
secret=$(echo ${2} | base64 --decode);
secretName="frost_notification";
registryURL="https://index.docker.io/v1/";
imageName="kdisneur/frost_notification";
containerName="frost_notification";

function deleteAllSecrets {
  if docker secret ls | grep -q ${secretName}; then
    docker secret ls --filter name=${secretName} --format '{{.Name}}' \
      | xargs docker secret rm;
  fi
}

if docker service ls | grep -q ${containerName}; then
  oldName=$(docker secret ls -f name=${secretName} --format '{{.Name}}');
  newName=$(mktemp "${secretName}_XXXXXX");
  echo ${secret} | docker secret create ${newName} -;

  docker service update \
    --secret-rm ${oldName} \
    --secret-add src=${newName},target=${secretName} \
    --image ${imageName}:${tag} \
    --with-registry-auth \
    ${containerName};

  docker secret rm ${oldName};
else
  deleteAllSecrets;

  newName=$(mktemp "${secretName}_XXXXXX");
  echo ${secret} | docker secret create ${newName} -;

  docker service create \
    --replicas 1 \
    --secret src=${newName},target=${secretName} \
    --name ${containerName} \
    --with-registry-auth \
    ${imageName}:${tag};
fi
